require("./init_d.js")
require("./init_c.js")
require("./moveTo_d.js")
require("./moveTo_c.js")
require("./putString_d.js")
require("./putString_c.js")
require("./clear_d.js")
require("./clear_c.js")
